#
# This is only meant to be used when developing locally, as a shortcut to
# setting up an environment for the integration tests.
#
# eg.: `docker-compose -f docker-compose-integration-testing.yaml up -d`
#

version: '2'

services:
  redis:
    image: redis:alpine
    container_name: gskp-redis
    ports:
      - '6379:6379'
  redis-auth:
    image: redis:alpine
    container_name: gskp-redis-auth
    command: --requirepass password
    ports:
      - '6380:6379'
