---

# This is an example YAML config file.

# The config file can be written in YAML, TOML or JSON and needs to be named
# `config.ext` (eg. `config.yaml`)

# The config file can be placed in the same path with the binary or in `./conf`

# Configuration values can be overriden using environment variables. The name
# of the environment variables is prefixed by GSKP_, eg:
# githubAccessToken is controlled by GSKP_GITHUBACCESSTOKEN

organizationName: my_github_organization_name
teamName: team_whose_members_get_ssh_access
githubAccessToken: token_to_use_with_the_github_api

# by default, it uses ":6379" to connect to redis (localhost), you can change
# this value by changing the value below
# redisHost: :6379
